# Generated by Django 5.1.4 on 2025-01-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_userprofile_email_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='firebase_uid',
            field=models.CharField(default=2, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
