# Generated by Django 5.1.4 on 2025-01-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_userprofile_firebase_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='firebase_uid',
        ),
    ]
