# Generated by Django 5.1.4 on 2025-01-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_userprofile_firebase_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='firebase_uid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
