# Generated by Django 5.1.4 on 2025-01-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_userprofile_firebase_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='video',
        ),
    ]
