# Generated by Django 5.1.4 on 2025-02-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_movies_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
