# Generated by Django 5.1.4 on 2025-02-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_movies_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
