# Generated by Django 5.1.4 on 2025-03-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_movies_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
