# Generated by Django 5.1.4 on 2025-03-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_movies_rating_movies_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
