# Generated by Django 5.1.4 on 2025-04-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
