# Generated by Django 5.1.4 on 2025-04-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_movies_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.CharField(blank=True, choices=[('Action', 'Action'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Horror', 'Horror'), ('Thriller', 'Thriller'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi')], default='Drama', max_length=100, null=True),
        ),
    ]
