# Generated by Django 5.1.4 on 2025-04-04 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_categories_alter_movies_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
