# Generated by Django 5.1.4 on 2025-04-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_delete_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
