# Generated by Django 5.1.4 on 2025-04-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, to='backend.movies'),
        ),
    ]
