# Generated by Django 5.1.4 on 2025-04-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_type_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cast_images/')),
                ('movies', models.ManyToManyField(blank=True, null=True, to='backend.movies')),
            ],
        ),
    ]
