# Generated by Django 5.1.4 on 2025-04-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_remove_movies_banner_watchhistory_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
