# Generated by Django 5.1.4 on 2025-04-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_movies_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchhistory',
            name='watched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
